routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PDFController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::group(['middleware' => ['auth']], function () {

    //CRUD Category
    Route::get('/category', [CategoryController::class, 'index']);
    Route::post('/category', [CategoryController::class, 'store']);
    Route::delete('/category/{id}', [CategoryController::class, 'destroy']);
    Route::get('/category/{id}/edit', [CategoryController::class, 'edit']);
    Route::patch('/category/{id}', [CategoryController::class, 'update']);

    //CRUD Product
    Route::get('product', [ProductController::class, 'index']);
    Route::get('product/create', [ProductController::class, 'create']);
    Route::post('product', [ProductController::class, 'store']);
    Route::get('product/edit', [ProductController::class, 'edit']);
    Route::post('product/{product_id}', [ProductController::class, 'update']);
    Route::get('product/{product_id}/show', [ProductController::class, 'show']);
    Route::resource('product', ProductController::class);

    //CRUD Profile
    Route::get('/profile/{id}/show', [ProfileController::class, 'index']);
    Route::patch('/profile/{id}', [ProfileController::class, 'update']);

    //Customer
    Route::get('/products', [CustomerController::class, 'index']);
    Route::get('/search-products={product_name}', [ProductController::class, 'search']);
    Route::get('/products/category/{category_id}', [CategoryController::class, 'showProductByCategory']);
    Route::get('/myorders', [CustomerController::class, 'order_index']);

    //Cart
    Route::post('/add-to-cart/{user_id}/{product_id}', [CartController::class, 'addToCart']);
    Route::post('/subtract-quntity/{user_id}/{product_id}', [CartController::class, 'subtractCartItemQuantity']);
    Route::post('/add-quntity/{user_id}/{product_id}', [CartController::class, 'addCartItemQuantity']);

    //Order
    Route::get('/checkout', [OrderController::class, 'index']);
    Route::post('/order', [OrderController::class, 'store']);

    //PDF
    Route::get('/download-invoice/{order_id}', [PDFController::class, 'generatePDF']);
});

Auth::routes();

resources/views/dashboard/polluxui/admin/category.blade.php
@extends('dashboard.polluxui.partials.master')

@section('title')
    Store Categories
@endsection

@section('content')
    @if (Auth::user()->role == 'admin')
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body justify-content-center">
                    <h4 class="card-title">Add New Product Category</h4>
                    <p class="card-description">
                        Insert new product category here
                    </p>
                    <form action="/category" method="post" class="form-inline d-flex justify-content-between">
                        @csrf
                        @method('post')
                        <label class="sr-only" for="inlineFormInputName2">Category</label>
                        <input type="text" class="col-10 form-control mb-2" name="name" id="inlineFormInputName2"
                            placeholder="Electronic">
                        <button type="submit" class="btn btn-primary mb-2">Add Category</button>

                        @if ($errors->has('category'))
                            <div class="col-12 alert alert-danger">
                                <p>{{ $errors->first('category') }}</p>
                            </div>
                        @endif
                    </form>
                </div>
            </div>
        </div>

        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">List Category</h4>
                    <p class="card-description">
                        See available product category in our shop
                    </p>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">No</th>
                                    <th class="text-center">Category Name</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($categories as $key => $item)
                                    <tr>
                                        <td class="text-center">{{ $key + 1 }}</td>
                                        <td class="text-left">{{ $item->name }}</td>
                                        <td class="d-flex justify-content-center">

                                            <form action="/category/{{ $item->id }}" method="post">
                                                @csrf
                                                @method('delete')

                                                <a href="/category/{{ $item->id }}/edit">
                                                    <button type="button" class="btn btn-info btn-icon-text mx-2">
                                                        Edit
                                                        <i class="typcn typcn-edit btn-icon-append"></i>
                                                    </button>
                                                </a>

                                                <a href="/products/category/{{ $item->id }}">
                                                    <button type="button" class="btn btn-warning btn-icon-text mx-2">
                                                        <i class="typcn typcn-shopping-bag btn-icon-prepend"></i>
                                                        See Products
                                                    </button>
                                                </a>

                                                <button type="submit" class="btn btn-danger btn-icon-text mx-2">
                                                    <i class="typcn typcn-trash btn-icon-prepend"></i>
                                                    Delete
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3" class="text-center">There's no category</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="container-scroller">
            <div class="container-fluid page-body-wrapper full-page-wrapper">
                <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
                    <div class="row flex-grow">
                        <div class="col-lg-7 mx-auto text-white">
                            <div class="row align-items-center d-flex flex-row">
                                <div class="error-page-divider text-lg-left pl-lg-4">
                                    <h2>SORRY! You dont have access :)</h2>
                                </div>
                            </div>
                            <div class="row mt-5">
                                <div class="col-12 text-center mt-xl-2">
                                    <a class="text-white font-weight-medium" href="{{ url('product') }}">Back to home</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif
@endsection

resources/views/dashboard/polluxui/admin/create-product.blade.php
@extends('dashboard.polluxui.partials.master')

@section('title')
Create Product
@endsection

@section('content')
@if (Auth::user()->role == 'admin')
<br>
<h3>Insert Product</h3>
<br>
<div class="card mb-4">
    <div class="formcreate m-5">
        <form action="{{ url('product') }}" enctype="multipart/form-data" method="POST">
            @csrf
            <div class="mb-3">
                <label>Nama Produk</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="name">
            </div>
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Masukkan Kategori Produk</label>
                <br>
                <select name="category_id">
                    <option disabled>-- Pilih Kategori Produk --</option>
                    @foreach ($category as $item)
                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                    @endforeach
                </select>
            </div>
            @error('category')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Stock</label>
                <input type="number" class="form-control" id="exampleInputPassword1" name="stock">
            </div>
            @error('stock')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Deskripsi Produk</label>
                <input type="text" class="form-control" id="exampleInputPassword1" name="description">
            </div>
            @error('description')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Gambar Produk</label>
                <input type="file" class="form-control" id="exampleInputPassword1" name="picture">
            </div>
            @error('picture')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Harga Produk</label>
                <input type="number" class="form-control" id="exampleInputPassword1" name="price">
            </div>
            @error('price')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <button type="submit" class="btn btn-primary" onclick="return confirm('Apakah Data yang Anda Masukkan Sudah Benar?')">Submit</button>
        </form>
    </div>
</div>
@else
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
            <div class="row flex-grow">
                <div class="col-lg-7 mx-auto text-white">
                    <div class="row align-items-center d-flex flex-row">
                        <div class="error-page-divider text-lg-left pl-lg-4">
                            <h2>SORRY! You dont have access :)</h2>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12 text-center mt-xl-2">
                            <a class="text-white font-weight-medium" href="{{ url('product') }}">Back to home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/dashboard/polluxui/admin/edit-category.blade.php
@extends('dashboard.polluxui.partials.master')

@section('title')
    Store Categories
@endsection

@section('content')
@if (Auth::user()->role == 'admin')
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body justify-content-center">
                <h4 class="card-title">Edit Product Category</h4>
                <p class="card-description">
                    Edit Product Category here
                </p>
                <form action="/category/{{$category->id}}" method="post" class="form-inline d-flex justify-content-between">
                    @csrf
                    @method('patch')
                    <label class="sr-only" for="inlineFormInputName2">Category</label>
                    <input type="text" class="col-10 form-control mb-2" name="name" id="inlineFormInputName2"
                        placeholder="{{$category->name}}" value={{$category->name}}>
                    <button type="submit" class="btn btn-primary mb-2">Edit Category</button>

                    @if ($errors->has('category'))
                        <div class="col-12 alert alert-danger">
                            <p>{{ $errors->first('category') }}</p>
                        </div>
                    @endif
                </form>
            </div>
        </div>
    </div>

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">List Category</h4>
                <p class="card-description">
                    See available product category in our shop
                </p>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Category Name</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($categories as $key => $item)
                                <tr>
                                    <td class="text-center">{{ $key + 1 }}</td>
                                    <td class="text-left">{{ $item->name }}</td>
                                    <td class="d-flex justify-content-center">

                                        <form action="/category/{{$item->id}}" method="post">
                                            @csrf
                                            @method('delete')

                                            <button type="button" class="btn btn-info btn-icon-text mx-2">
                                                Edit
                                                <i class="typcn typcn-edit btn-icon-append"></i>                                                                              
                                              </button>
    
                                              <button type="button" class="btn btn-warning btn-icon-text mx-2">
                                                <i class="typcn typcn-shopping-bag btn-icon-prepend"></i>                                                    
                                                See Products
                                              </button>
    
                                            <button type="submit" class="btn btn-danger btn-icon-text mx-2">
                                                <i class="typcn typcn-trash btn-icon-prepend"></i>                                                    
                                                Delete
                                              </button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="text-center">There's no category</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @else
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
                <div class="row flex-grow">
                    <div class="col-lg-7 mx-auto text-white">
                        <div class="row align-items-center d-flex flex-row">
                            <div class="error-page-divider text-lg-left pl-lg-4">
                                <h2>SORRY! You dont have access :)</h2>
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-12 text-center mt-xl-2">
                                <a class="text-white font-weight-medium" href="{{ url('product') }}">Back to home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif
    @endsection

resources/views/dashboard/polluxui/admin/edit-product.blade.php
@extends('dashboard.polluxui.partials.master')

@section('title')
Edit Product
@endsection

@section('content')
@if (Auth::user()->role == 'admin')
<br>
<h3>Edit Product</h3>
<br>
<div class="card mb-4">
    <div class="formcreate m-5">
        <form action="{{ route('product.show', $product->id) }}" enctype="multipart/form-data" method="POST">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label>Nama Produk</label>
                <input type="text" class="form-control" id="exampleInputEmail1" value="{{ $product->name }}" name="name">
            </div>
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Masukkan Kategori Produk</label>
                <br>
                <select name="category_id">
                    <option disabled>-- Pilih Kategori Produk --</option>
                    @foreach ($category as $item)
                    @if ($item->id === $product->category_id)
                        <option value="{{ $item->id }}" selected>{{ $item->name }}</option>
                    @else 
                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                    @endif
                    @endforeach
                </select>
            </div>
            @error('category_id')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Stock</label>
                <input type="number" class="form-control" value="{{ $product->stock }}" id="exampleInputPassword1" name="stock">
            </div>
            @error('stock')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Deskripsi Produk</label>
                <input type="text" class="form-control" value="{{ $product->description }}" id="exampleInputPassword1" name="description">
            </div>
            @error('description')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Gambar Produk</label>
                <input type="file" class="form-control" id="exampleInputPassword1" name="picture" value="{{ $product->picture }}">
            </div>
            @error('picture')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <div class="mb-3">
                <label>Harga Produk</label>
                <input type="number" class="form-control" value="{{ $product->price }}" name="price">
            </div>
            @error('price')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@else
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
            <div class="row flex-grow">
                <div class="col-lg-7 mx-auto text-white">
                    <div class="row align-items-center d-flex flex-row">
                        <div class="error-page-divider text-lg-left pl-lg-4">
                            <h2>SORRY! You dont have access :)</h2>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12 text-center mt-xl-2">
                            <a class="text-white font-weight-medium" href="{{ url('product') }}">Back to home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/dashboard/polluxui/admin/index-product.blade.php
@extends('dashboard.polluxui.partials.master')

@section('content')
@if (Auth::user()->role == 'admin')
<div class="col-12 grid-margin stretch-card">
  <div class="card">
      <div class="card-body justify-content-center">
          <h4 class="card-title">Add New Product Product</h4>
          <div class="d-flex justify-content-between">
            <div class="description">
          <p class="card-description">
              Insert new product here
          </p>
        </div>
        <div class="tomboladd">
          <a href="{{ route('product.create') }}" type="submit" class="btn btn-primary">Tambah Product</a>
        </div>
        </div>
      </div>
  </div>
</div>

<div class="card mb-4">
  <div class="card-header">
      Data Product
  </div>
  <div class="table-responsive">
      <table class="table table-striped m-3">
          <thead>
              <tr>
                  <th scope="col">No</th>
                  <th scope="col">Name</th>
                  <th scope="col">Stock</th>
                  <th scope="col">Description</th>
                  <th scope="col">Price</th>
                  <th scope="col">Action</th>
              </tr>
          </thead>
          <tbody>
              @foreach ($product as $key => $item)

              <tr>
                  <td>{{ $key + 1 }}</td>
                  <td>{{ $item->name }}</td>
                  <td>{{ $item->stock }}</td>
                  <td>{{ $item->description }}</td>
                  <td>{{ $item->price }}</td>
                  <td>
                      <form action="{{ url('product',$item->id) }}" method="POST">
                          @csrf
                          @method('delete')
                          <a href="{{ route('product.show',$item->id) }}" type="submit" class="btn btn-info btn-sm mx-2">Detail Product</a>
                          <a href="{{ route('product.edit',$item->id) }}" type="submit" class="btn btn-warning btn-sm mx-2">Edit Product</a>
                          <input type="submit" class="btn btn-danger btn-sm mx-2" value="DELETE" onclick="return confirm('Data Akan Dihapus?')">
                      </form>
                  </td>
              </tr>
              @endforeach
          </tbody>
      </table>
  </div>
</div>
@else
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
            <div class="row flex-grow">
                <div class="col-lg-7 mx-auto text-white">
                    <div class="row align-items-center d-flex flex-row">
                        <div class="error-page-divider text-lg-left pl-lg-4">
                            <h2>SORRY! You dont have access :)</h2>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12 text-center mt-xl-2">
                            <a class="text-white font-weight-medium" href="{{ url('product') }}">Back to home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endif
@endsection